### PR TITLE
Editing of #308 and #313 (parts of #314)

### PR DESCRIPTION
**Pull request by tradej**
Someone please have a look, I am not sure if I kept the meaning of all the sentences. Thank you.

Relates to #308, #313, and #314.

### CODE REVIEW

**Comment by tradej** [comment]
Note: I am not exactly sure if we should use both _container_ and _pod_ in the text. IMO we should only use one, but I am not sure if they are used interchangeably here.

**Comment by Ladicek** [comment]
The terms _pod_ and _container_ are __not__ interchangeable. Basically, pod is a set of colocated containers that are managed as a single unit.

**Comment by tradej** [comment]
Thank you, @Ladicek. I have updated the wording accordingly.

**Comment by edewit** [comment]
:+1: on the content, this was extracted from the index.html of the boosters we wanted to have an automatic way of updating them unfortunately for heath check this is not yet in place so once merged we need to update:
http://github.com/snowdrop/spring-boot-health-check-booster
https://github.com/openshiftio-vertx-boosters/vertx-health-checks-booster
https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-health-check

**Comment by rhoads-zach** [comment]
Merging.

**Comment by rhoads-zach** [comment]
merged: https://github.com/openshiftio/appdev-documentation/commit/0cec512f42820b94bed5236779060011bb20e0e5

**Comment by edewit** [comment]
@tradej this doc is for all the boosters, didn't see it the first time, but we shouldn't put vertx in the title

**Comment by rhoads-zach** [comment]
merged: https://github.com/openshiftio/appdev-documentation/commit/f8579c477b1828d19915bd26dbec4b555916ecf0

**Pull request closed without merging**
