### PR TITLE
Update: added first draft of sb runtime details

### PR DESCRIPTION
**Pull request by rhoads-zach**
@cmoulliard @inoxx03 mind taking a look?

### CODE REVIEW

**Comment by Ladicek** [comment]
CC @RadekKoubsky

**Comment by cmoulliard** [comment]
> taking a look?

Looks good to me @rhoads-zach . We should perhaps  for all the runtimes include a paragraph where we will explain the added value to run the different runtimes on OpenShift, what should be changed within an existing project to transform it into a compatible project deployable on Openshift (= f-m-p plugin, ....), what will happen during the build (= target folder zipped and pushed to openshift, s2i build started using the Java S2I image to copy/paster and customize the docker image created, create an imagestream which is next used with the DeploymentConfig to install the application

**Comment by inoxx03** [comment]
merging

**Comment by inoxx03** [comment]
merged: 5338ba695e4b2047764c0fb86e9c998bdc84ff79

**Pull request closed without merging**
