### PR TITLE
Fixes #638

### LINKED ISSUE #638: Document keycloak configuration process

### PR DESCRIPTION
**Pull request by rhoads-zach**
@gastaldi @ALRubinger let me know what you think.

### CODE REVIEW

**Comment by rhoads-zach** [comment]
thanks @gastaldi 

@tradej feel free to merge

**Comment by rhoads-zach** [comment]
thanks for the feedback @tradej, feel free to merge.

**Comment by tradej** [comment]
OK. Merging.

**Comment by tradej** [comment]
merged: 0db38b4

**Pull request closed without merging**
