### PR TITLE
Issue #616: added note about code download

### LINKED ISSUE #616: SpringBoot, VertX, Swarm booster chapters - note about code download
There should be some note at the beginning of every mission chapter where to download code what is chapter about.
For example 'Code can be downloaded from launchpad...select booster xy and download the code in zip....

Just to know and see code what is chapter about.

### PR DESCRIPTION
**Pull request by inoxx03**
resolves #616 

@liborfuka @Ladicek: Would a note like this be OK? Since we have the ZIP download instructions already documented I included a link to the appropriate section of the GSG.
Please let me know WDYT and if it's ok, I'll include the note at the top of each Mission chapter. 

As I mentioned in the discussion on #616, there is also the alternative of linking directly to the repo on GitHub that hosts the booster code.

### CODE REVIEW

**Comment by Ladicek** [comment]
Yea I think this makes sense. No need to repeat the instructions we already describe elsewhere.

**Comment by Ladicek** [comment]
LGTM. @liborfuka WDYT?

**Comment by liborfuka** [comment]
I think its sufficient note and #616 can be resolved.

**Comment by rhoads-zach** [comment]
merged: 08f03b521b529e4d700e8789af31598072ce0198

**Pull request closed without merging**
