### PR TITLE
Issue #430: Added resources section to secured mission guide

### LINKED ISSUE #430: Create an Additional Resources Section in the Secured booster guides
Since all the other mission have these section, it might help to keep the Secured Mission (despite its slightly different structure) guide consistent and add a similar section to it, too.

### PR DESCRIPTION
**Pull request by inoxx03**
@Ladicek  @rhoads-zach WDYT?

Resolves #430 

I'll see if I can find any other sources that we could link to from this section, and add them

### CODE REVIEW

**Comment by Ladicek** [comment]
A link to Keycloak docs and/or Red Hat SSO docs?

**Comment by inoxx03** [comment]
@Ladicek Thanks, I added a link to docs for  RHSSO 7.1 and Keycloak 3.2.

**Comment by inoxx03** [comment]
@rhoads-zach Please feel free to merge, if it looks ok to you.

**Comment by rhoads-zach** [comment]
LGTM, merging.

**Comment by rhoads-zach** [comment]
merged: f6c2d3afd3b4dc90fca133441936c6971fdc041e

**Pull request closed without merging**
