### PR TITLE
Renamed all scripts to lower case & underscores

### LINKED ISSUE #440: Consolidate script naming
There is a discrepancy in the script naming scheme:

* Most of the scripts in the `scripts` directory and the `buildGuide.sh` scripts are named in camelCase.
* `scripts/deploy_launchpad_mission.sh` and `cico_build_deploy.sh` are named using underscores.

Let's consolidate the naming conventions of the scripts. I suggest we use the all-lowercase, underscore-separated naming:
```
scripts/build_guides.sh
scripts/build_guides_ci.sh
scripts/deploy_launchpad_mission.sh

etc.
```

WDYT?

### PR DESCRIPTION
**Pull request by tradej**
Contents:

* All scripts now use the same file naming: all lowercase and underscores.
* All references to said scripts are updated as well
* The commits are atomic, i. e. the contain the renaming of only one script and all references to that script. For that reason, please do not squash.

Resolves #440.

### CODE REVIEW

**Comment by tradej** [comment]
Waiting for #488 to be merged first.

**Comment by tradej** [comment]
Waiting for #503 to be merged first.

**Comment by tradej** [comment]
Ready for review.

**Comment by inoxx03** [comment]
merging

**Comment by inoxx03** [comment]
(squashed and) merged: 08b406b00d2cf86141d5704f9c5f9dd7be1b8a04

**Pull request closed without merging**
