### PR TITLE
New Publishing Information + Removed Legacy Files

### LINKED ISSUE #377: Write missing chapters in the Contribution Guide
Currently missing chapters:

* Metadata and Attributes
* Requirements (naming, supportability statements, legal requirements etc.)
* Internal JIRA issues workflow
* ~~Publishing~~

Follows up on #376, resolves #239.

### LINKED ISSUE #439: Remove unnecessary files
Once the Nginx move is finished, the following files or directories will not be necessary any more, and can be purged:
```
ci/
scripts/dockerTagRelease.sh
```

Dependent on #428.

### PR DESCRIPTION
**Pull request by tradej**
Contents:

* Unnecessary files removed (fixes #439).
  * The entire `$REPO_HOME/ci` directory.
  * `previewDocsServer.sh` and `dockerTagRelease.sh` in `$REPO_HOME/scripts`.
* Moved the contents of `RELEASE.adoc` to the Contrib Guide.
* Made changes based on the new workflow.
* Added instructions about publishing via `openshiftio/saas-launchpad`.

Resolves #439 and #477.
Partially resolves #377.

### CODE REVIEW

**Comment by inoxx03** [comment]
@tradej Heads up: Upon doing `$ sudo CICO_LOCAL=true ./cico_build_deploy.sh`, the Contrib guide fails to validate.

**Comment by tradej** [comment]
Thanks for the reviews.

I have fixed the issue, and added a small section about validating your books before submitting in `contributing-making-changes.adoc`.

**Comment by tradej** [comment]
@inoxx03 I believe so, thank you.

**Comment by inoxx03** [comment]
merging

**Comment by inoxx03** [comment]
merged: 7a89b710a0467454cfa6326011608466dfa38f43

**Pull request closed without merging**
