### PR TITLE
Update: Added runtime details for vertx

### PR DESCRIPTION
**Pull request by rhoads-zach**
@inoxx03 and @cescoffier 

mind taking a look?

### CODE REVIEW

**Comment by Ladicek** [comment]
Looks good to me, but CC @SlavoKrupa anyway.

**Comment by SlavoKrupa** [comment]
Looks good to me 👍

**Comment by inoxx03** [comment]
merging

**Comment by inoxx03** [comment]
merged: 09782726e825bc79fa13a85289f1daef2c28db56

**Pull request closed without merging**
