### PR TITLE
updated description for npm install

### PR DESCRIPTION
**Pull request by lavernw1**
Resolves Issue 522.  @Ladicek I incorporated your comments regarding npm_install for the nodejs runtime. Please review. Thanks.

### CODE REVIEW

**Comment by rhoads-zach** [comment]
changes LGTM.

**Comment by Ladicek** [comment]
Thanks. I'm not a native speaker, so I can't tell if there's a difference between your

> then using the Nodeshift package, launch the S2I process on {OpenShiftLocal} to start the pod.

and my suggestion of

> then, using the Nodeshift package, launch the S2I process on {OpenShiftLocal} to start the pod.

(Just an extra comma.)

Also not sure if "launch the S2I process to start the pod" is still an acceptable simplification, but I guess yes; we can't describe how OpenShift work in each and every sentence :-)

So LGTM.

**Comment by inoxx03** [comment]
@Ladicek AFAIK, the second option with the extra comma is the correct one:) Fortunately, the missing comma here does not shift the meaning of the sentence, so it isn't a big problem. Sorry about the nitpick :)

**Comment by lavernw1** [comment]
Thanks @Ladicek @rhoads-zach @inoxx03 for the review of changes.

**Comment by inoxx03** [comment]
merged: 41d29063b23611a6f5a2c87b84bfa421a7f2a0de

**Pull request closed without merging**
