### PR TITLE
Fixes #658

### LINKED ISSUE #658: Update GSG paragraph around minishift
Update Intro paragraph here: https://appdev.prod-preview.openshift.io/docs/getting-started.html#_build_and_deploy_using_single_node_openshift_cluster

Update for build and deploy

### PR DESCRIPTION
**Pull request by rhoads-zach**
FYI @cmoulliard

### CODE REVIEW

**Comment by cmoulliard** [comment]
I think that we should still improve 2 thinks

1) Build
"In addition to building on your local machine and pushing to a local or public cloud, you also have the ability to build and deploy your booster directly to {OpenShiftLocal}." --> We explain twice the same concept but for local build vs on openshiftlocal. This is confusing. With f-m-p you build your java application and deploy on Openshift no matter where OpenShift is running; that could be locally, remotely, ...  

2) Launcher
"Specifically, you can use the {launcher} application to clone a new booster repository to your GitHub account and have it deployed to your {OpenShiftLocal} using the Build and Deploy process." --> Is it documented/described somewhere what is the launcher, what a developer can achieve with the launcher ? Is still "launcher" the appropriate word to be used ?

**Comment by rhoads-zach** [comment]
@cmoulliard let me know what you think.

**Comment by tradej** [comment]
[test]

**Comment by inoxx03** [comment]
merged: 406ccc9de5c099c5b42b420ae89b9ddefbc81de4

**Pull request closed without merging**
