### PR TITLE
Cleanup: fix cloud-natve -> cloud native

### PR DESCRIPTION
**Pull request by rhoads-zach**

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@ALRubinger @jclingan mind taking a look and giving a +1?

**Comment by ALRubinger** [comment]
I've seen it used both ways, with "cloud-native" in line with Pivotal, VMWare; by contrast https://www.cncf.io/ does not hyphenate.

**Comment by rhoads-zach** [comment]
@ALRubinger I'm fine with either as long as we are consistent.

If we want to go "cloud-native" i'll close the PR, if we want to go "cloud native" i'll merge it.

@jclingan preference?

**Comment by rhoads-zach** [comment]
Merged: https://github.com/openshiftio/appdev-documentation/commit/43133a0979251ac0879ee29d49f4fc99e8a91771

**Pull request closed without merging**
