### PR TITLE
Cleanup: added note about oc version

### PR DESCRIPTION
**Pull request by rhoads-zach**
addressed comment in #175

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@SlavoKrupa mind taking a look?

**Comment by SlavoKrupa** [comment]
👍 Great! Thanks

**Comment by SlavoKrupa** [comment]
I have just realized that there is also interaction with OpenShift Online via client. ( AFAIK this covers only `oc` from minishift ) But users do not have to use whole minishift if they want just try cloud integration. They would only need `oc` binary which is also available at:
https://github.com/openshift/origin/releases/tag/v1.4.1

**Comment by SlavoKrupa** [comment]
I have just realized that there is also interaction with OpenShift Online via client. ( AFAIK this covers only `oc` from minishift ) But users do not have to use whole minishift if they want just try cloud integration. They would only need `oc` binary which is also available at:
https://github.com/openshift/origin/releases/tag/v1.4.1

**Comment by rhoads-zach** [comment]
@SlavoKrupa do you want me to hold this PR? or can i merge it?

**Comment by rhoads-zach** [comment]
@SlavoKrupa please file a separate issue for the oc client outside of minishift. merging.

**Comment by rhoads-zach** [comment]
merged: https://github.com/openshiftio/appdev-documentation/commit/9c4139d9b57e414debbf52194a745dfa8f79cc72

**Pull request closed without merging**
