### PR TITLE
fixes #637

### LINKED ISSUE #637: Refactor instructions and mentions of pipelines

### PR DESCRIPTION
**Pull request by rhoads-zach**

### CODE REVIEW

**Comment by tradej** [comment]
Took the liberty to change *increment* to *increase* as *increment* is technically a noun. Merging.

**Comment by Ladicek** [comment]
I think all developers are used to using _increment_ as a verb, and some dictionaries also list it as a verb, but interesting :-)

**Comment by tradej** [comment]
@Ladicek I'm well aware that's the case, but it's technical jargon, which should be avoided in documentation unless necessary.

**Comment by tradej** [comment]
merged: 1488c4

**Pull request closed without merging**
