### PR TITLE
Fixed headings

### LINKED ISSUE #647: Check capitalisation of headings for consistency
This is important for downstream docs. See [e-mail](http://post-office.corp.redhat.com/archives/content-services-list/2017-September/msg00183.html) (internal).

### PR DESCRIPTION
**Pull request by tradej**
Performed the following fixes in headings:

* Uppercasing/lowercasing as necessary [Chicago Manual of Style]
* Replaced "your" and "this" with "the" [Minimalism]
* Converted imperatives to gerunds [RH Stylepedia]

I am fairly sure I did not break any xrefs, but I think we should create explicit IDs for all headings anyway. However, that's definitely out of the scope of #647.

Resolves #647.

### CODE REVIEW

**Comment by tradej** [comment]
[test]

**Comment by tradej** [comment]
[test]

**Comment by rhoads-zach** [comment]
LGTM, nice work @tradej

**Comment by rhoads-zach** [comment]
merged: f41ab6e5effcbc5c4f02908b63cae702022ddf43

**Pull request closed without merging**
