### PR TITLE
Issue #243: updated GSG

### LINKED ISSUE #243: Document: The Developer Journey
Write up our value-add!

The general story arc takes a new developer from nothing into CD, with explanations behind:
* Building and deploying locally on host
* Building locally on host, baking and deploying on local cloud
* Building and deploying on OSO

Should be told as a story in easily-consumable manner - the website version of a conference talk

RHT internal reference: https://issues.jboss.org/browse/OBST-240

### PR DESCRIPTION
**Pull request by rhoads-zach**
resolves #243

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@tradej feel free to take an editing pass suggest changes.

**Comment by rhoads-zach** [comment]
@tradej merging to include in this week's updates. Feel free to file a follow-up PR with any editing changes.

**Comment by rhoads-zach** [comment]
merged: https://github.com/openshiftio/appdev-documentation/commit/1a479b29388a8dcda79229d13c28a2327e6d6084

**Comment by tradej** [comment]
Okay, I'll file a PR.

**Pull request closed without merging**
