### PR TITLE
Fixes #535

### LINKED ISSUE #535: remove authenticated but not authorized interaction from SSO missions

### PR DESCRIPTION
**Pull request by rhoads-zach**

### CODE REVIEW

**Comment by rhoads-zach** [comment]
nice catch @Ladicek, fixing now

**Comment by rhoads-zach** [comment]
@Ladicek fixed, let me know what you think

**Comment by Ladicek** [comment]
Maybe there are some other references to this flow, not sure, but I think this is good for now.

**Comment by rhoads-zach** [comment]
thanks @Ladicek merging.

**Comment by rhoads-zach** [comment]
merged:b5e71f5ce93c8d9ced6464eae4ff90d685f00ce6

**Pull request closed without merging**
