### PR TITLE
DO NOT MERGE - Issue OBST-209. Add asciidoctor-default.css

### PR DESCRIPTION
**Pull request by cmoulliard**
- Add asciidoctor-default.css style and 
- Change  document-attributes.adoc to use it `:stylesheet: asciidoc-default.css`

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@ALRubinger @cmoulliard @edewit thoughts on changes here vs. the current style?

**Comment by ALRubinger** [comment]
I'm a bit lost on these changes too. :)  Ultimately I think we need to devise a closer openshift.io look.  @cmoulliard mind explaining the motivations behind this one?  Or were ya just inspired? :D

**Comment by heiko-braun** [comment]
The readability of the contents improved, but the branding elements (header, footer, etc) are broken (or disappeared)

**Comment by cmoulliard** [comment]
> are broken (or disappeared)

I will have a look.

**Comment by cmoulliard** [comment]
> mind explaining the motivations behind this one?

Such css styles are coming from my previous experience with GPTE team where we designed many courses, labs, .. content using asciidoctor. Open Sans font used by Pattern Fly is not great to render such course content. This is why I'm proposing as alternative to use the asciidoctor default css or foundation css.

**Comment by heiko-braun** [comment]
@cmoulliard I agree that the styles you propose improve readability, but we need to recover the branding elements

**Comment by heiko-braun** [comment]
@cmoulliard I think it's just the header that disappeared:
screen shot 2017-04-21 at 17 08 17

**Comment by cmoulliard** [comment]
Header and footer enabled again for foundation.css and asciidoctor-default.css

screenshot 2017-04-21 17 10 24

**Comment by edewit** [comment]
👍 like it, good to merge

**Comment by ALRubinger** [comment]
7093dd2 Still a ways to go I think, but the rendering here is a marked improvement; thanks all!

**Pull request closed without merging**
