### PR TITLE
Issue #359: added conditional logic to link directly to the approprea…

### PR DESCRIPTION
**Pull request by rhoads-zach**
…te runtime guide

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@gastaldi I updated this to show the right guide link in the front end given the zip download flow. Is there any steps you need to do on your side to enable the {runtime} substitution?

**Comment by gastaldi** [comment]
@rhoads-zach no need to change anything in the addon or mission-control. runtime is already a template variable. See https://github.com/openshiftio/launchpad-addon/blob/master/src/main/java/io/openshift/launchpad/ui/booster/ProjectInfoStep.java#L243

**Comment by rhoads-zach** [comment]
thanks @gastaldi 

@inoxx03 feel free to merge after review.

**Comment by inoxx03** [comment]
merged: 4effa5122957e3e92f042103c239c4fc6b0da475

**Pull request closed without merging**
