### PR TITLE
updated urls for HTTP API Level 0

### PR DESCRIPTION
**Pull request by rhoads-zach**
per https://github.com/obsidian-toaster/documentation/wiki/HTTP-API-Level-0-Experience

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@inoxx03 please take a look and let me know what you think

**Comment by rhoads-zach** [comment]
@cescoffier mind taking a quick look?

**Comment by ALRubinger** [comment]
@rhoads-zach "api" namespace changes look good to me.

**Comment by rhoads-zach** [comment]
thank you @cescoffier i'm still seeing "id" in the quick starts for boot and wf-swarm. is that incorrect?

**Comment by ALRubinger** [comment]
99bddf0

**Comment by heiko-braun** [comment]
I think all urls should refer to `nip.io`, rather than `nio.io`

**Comment by ALRubinger** [comment]
Good catch @heiko-braun

**Comment by rhoads-zach** [comment]
nice catch @heiko-braun 

I updated the PR to use the correct urls

Mind taking a quick look and providing a thumbs up if it looks good?

**Comment by heiko-braun** [comment]
Looks good to me

**Comment by ALRubinger** [comment]
f736639a9ef0d55b74c5406ab21897b25c5f0988

**Pull request closed without merging**
