### PR TITLE
removed platform name

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by edewit** [comment]
automatic PR created to update the booster #9

**Comment by edewit** [comment]
automatic PR created to update the booster https://api.github.com/repos/snowdrop/spring-boot-http-booster/pulls/50

**Comment by edewit** [comment]
automatic PR created to update the booster https://api.github.com/repos/openshiftio-vertx-boosters/vertx-http-booster/pulls/10

**Comment by rhoads-zach** [comment]
merged: https://github.com/openshiftio/appdev-documentation/commit/de43cc39a8d667bed4b40b2e9554a9b4ba3f34a7

**Comment by openshiftio-launchpad** [comment]
automatic PR created to update the booster https://github.com/snowdrop/spring-boot-http-booster/pull/51

**Comment by openshiftio-launchpad** [comment]
automatic PR created to update the booster https://github.com/openshiftio-vertx-boosters/vertx-http-booster/pull/11

**Comment by openshiftio-launchpad** [comment]
automatic PR created to update the booster https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http/pull/16

**Pull request closed without merging**
