### PR TITLE
update getting started resource list and clean up

### PR DESCRIPTION
**Pull request by rhoads-zach**

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@kenfinnigan @ALRubinger mind giving me a +1?

**Comment by kenfinnigan** [comment]
+1

**Comment by ALRubinger** [comment]
@rhoads-zach Some way to comment out instead of removing?  Either way the end result is +1 from me: remove secured, remove configmap, remove healthcheck-boot.

**Comment by rhoads-zach** [comment]
@ALRubinger i'll re-add and comment out

**Pull request merged**
