### PR TITLE
Improved wording in S2I appendix

### LINKED ISSUE #670: Reword + improve complicated passages
Some parts of the docs, especially the introductions, are often quite verbose and hard to read, especially for newcomers to the topic. I believe we should reword these parts for improved readablility, among others:

* _General Missions intro:_ Very technical terms, long sentences that are hard to read.
* _REST API mission intro:_ Quite technical. Given it's the most basic of the missions, I believe it should be written in the most basic way.
* _Circuit Breaker intro sections:_ Long sentences that are hard to read.
* _WildFly Runtime details:_ Quite technical and some formulations are fairly vague, e. g. "just-enough-appserver".
* _Using a Nexus Repository Server With the launch.openshift.io Application on a Single-node OpenShift Cluster:_ Long sentences that are hard to read.

This is a follow-up issue to #309.

### PR DESCRIPTION
**Pull request by tradej**
* Put each sentence on a separate line ([Asciidoctor recommendation](http://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line)).
* Removed superfluous words.
* Minor fixes for consistency.

Partially resolves #670.

### CODE REVIEW

**Comment by Ladicek** [comment]
Should maybe "Builder" be "builder"?

**Comment by rhoads-zach** [comment]
@tradej @inoxx03 please hold this for now

**Comment by tradej** [comment]
@rhoads-zach, can we un-WIP and merge this?

**Comment by inoxx03** [comment]
merging...

**Comment by inoxx03** [comment]
merged: a151556bdc6ba24241f4dd2c5424137033f5f720

**Pull request closed without merging**
