### PR TITLE
added warning again

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by rhoads-zach** [comment]
[test]

**Comment by inoxx03** [comment]
@gastaldi @edewit made some writing-related changes to the note, factual content left intact. I also Replaced the window="_blank" syntax with a caret, since the former seemed to render the attribute visible along with the link text.

**Comment by rhoads-zach** [comment]
[test]

**Comment by inoxx03** [comment]
merging

**Comment by gastaldi** [comment]
Wait, it is missing an S in the URL: https://sso.openshift.io/auth/realms/rh-developers-launch/account/identity

**Comment by inoxx03** [comment]
@gastaldi, Nice catch:) thank you, will fix now:)

**Comment by inoxx03** [comment]
done, merging:)

**Comment by inoxx03** [comment]
merged: 61710fe4da4d9b771f63430ddea70732f0fcab36
(* please ignore the conflicts, they resulted from squashing the commits )

**Pull request closed without merging**
