### PR TITLE
fixed font-size attribute for fa icons in styles/foundation.css 

### LINKED ISSUE #163: Icons of font-awesome are too small
screenshot 2017-04-24 19 14 26

### PR DESCRIPTION
**Pull request by inoxx03**
fixes #163

### CODE REVIEW

**Comment by inoxx03** [comment]
@cmoulliard Please take a look.

**Comment by edewit** [comment]
:+1:

**Comment by rhoads-zach** [comment]
Merging.

**Comment by rhoads-zach** [comment]
Merged: https://github.com/openshiftio/appdev-documentation/commit/17147b14d053596537b3eab1818d6ad21cc9c3b3

**Pull request closed without merging**
